<?xml version="1.0"?>

<package format="3">

  <name>panda_pick_place</name>
  <version>0.0.1</version>

  <description>
    Panda robot pick and place using ROS 2 and MoveIt 2
  </description>

  <maintainer email="s.hussain@brighton.ac.uk">
    Sajjad Hussain
  </maintainer>

  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>moveit_msgs</depend>
  <depend>shape_msgs</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>

</package>
